import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', headless:true, args:['--headless=new','--no-sandbox'] })
const p = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:1.2 }).then(c=>c.newPage())
const errs=[]; p.on('pageerror',e=>errs.push(e.message))
await p.goto('http://localhost:4173/',{waitUntil:'networkidle'})
await p.evaluate(()=>localStorage.removeItem('pricecheck-edits-v1'))
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(1400)
await p.getByText('Несостыковки и правки',{exact:true}).click(); await p.waitForTimeout(700)
await p.getByRole('button',{name:/Нет в матрице/}).first().click(); await p.waitForTimeout(500)
await p.getByRole('button',{name:/Сопоставить/}).first().click(); await p.waitForTimeout(500)
await p.getByPlaceholder('Поиск планового товара…').fill('масло'); await p.waitForTimeout(400)
await p.screenshot({path:'m-modal.png'})
console.log('errors:', errs.length?errs.join('|'):'none')
await b.close()
